version: '3.7'
services:
  database:
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  catalog-microservice:
    build: ./catalog
    ports:
      - "81:80"
volumes:
  db:
    driver: local
