version: '3.7'
services:
  database:
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  user-microservice:
    build: ./user
    ports:
      - "80:80"
      # - "443:443"
  catalog:
    build: ./catalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "81:80"
      - "444:443"
volumes:
  db:
    driver: local
