version: '3.7'
services:
  database:
    image: postgres:alpine3.17
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  user-microservice:
    build: ./user
    ports:
      - "80:80"
    depends_on:
      - database
volumes:
  db:
    driver: local
