version: '3.7'
services:
  database:
    build: ./postgresql
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data
  user-microservice:
    build: ./user
    ports:
      - "80:80"
  catalog-microservice:
    build: ./catalog
    ports:
      - "81:80"
  data-importer:
    build: ./data-importer
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    depends_on:
      - database



volumes:
  db:
    driver: local
